FROM node:18-alpine

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

ENV NODE_ENV production
COPY . .

RUN pnpm install

RUN pnpm run --filter=via-scientific-frontend -r build

EXPOSE 3001
CMD ["pnpm", "run", "--filter=via-scientific-frontend", "-r", "preview", "--port", "3001"]